# Generated by Django 6.0.1 on 2026-01-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_add_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='confirmation_message_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
