# Generated by Django 6.0.1 on 2026-02-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_confirmation_message_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
