# Generated by Django 6.0.1 on 2026-02-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_waitlistentry_user_profile'),
        ('sales', '0006_saleitem_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.company'),
        ),
    ]
