# fly.toml app configuration file generated for auto-tuck-shop on 2026-01-21T15:26:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'auto-tuck-shop'
primary_region = 'iad'
console_command = '/code/manage.py shell'

[build]
  buildkit = true
  depot = false

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'
  DJANGO_SETTINGS_MODULE = 'config.settings.production'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = '/code/staticfiles'
  url_prefix = '/static/'
