# Generated by Django 6.0.1 on 2026-02-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_add_waitlist_confirmation_sid'),
        ('sales', '0005_add_confirmation_message_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('interactive_button', 'Interactive Button'), ('button_response', 'Button Response'), ('unknown', 'Unknown')], max_length=30)),
                ('phone_number', models.CharField(db_index=True, help_text='Normalized phone number with + prefix', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content', models.TextField(blank=True, help_text='Message text content')),
                ('button_id', models.CharField(blank=True, help_text='Button ID for button responses (e.g., confirm_123)', max_length=100)),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='Meta API message ID', max_length=100)),
                ('reply_to_message_id', models.CharField(blank=True, help_text='ID of message being replied to', max_length=100)),
                ('raw_payload', models.JSONField(blank=True, help_text='Full webhook/API response for debugging', null=True)),
                ('api_success', models.BooleanField(blank=True, help_text='Whether outbound message sent successfully', null=True)),
                ('api_error', models.TextField(blank=True, help_text='Error message if send failed')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='core.company')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='sales.sale')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='core.userprofile')),
                ('waitlist_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='core.waitlistentry')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['phone_number', '-timestamp'], name='whatsapp_wh_phone_n_3ae202_idx'), models.Index(fields=['direction', '-timestamp'], name='whatsapp_wh_directi_669e64_idx'), models.Index(fields=['user_profile', '-timestamp'], name='whatsapp_wh_user_pr_286f0a_idx'), models.Index(fields=['company', '-timestamp'], name='whatsapp_wh_company_a638ba_idx'), models.Index(fields=['sale'], name='whatsapp_wh_sale_id_a83a01_idx'), models.Index(fields=['waitlist_entry'], name='whatsapp_wh_waitlis_417fb9_idx')],
            },
        ),
    ]
