# Generated by Django 6.0.1 on 2026-02-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_id',
            field=models.CharField(blank=True, help_text='Meta media ID for audio/image/video', max_length=200),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_url',
            field=models.URLField(blank=True, help_text='CDN URL for media file (5-minute expiry)'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='transcribed_text',
            field=models.TextField(blank=True, help_text='Transcribed text from audio messages'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('interactive_button', 'Interactive Button'), ('button_response', 'Button Response'), ('audio', 'Audio'), ('unknown', 'Unknown')], max_length=30),
        ),
    ]
