# Generated by Django 6.0.1 on 2026-02-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappmessage_media_id_whatsappmessage_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='r2_media_url',
            field=models.URLField(blank=True, help_text='Permanent R2 storage URL for media file'),
        ),
    ]
