# Generated by Django 6.0.1 on 2026-02-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_add_r2_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='Normalized phone number with + prefix', max_length=25),
        ),
    ]
