# Generated by Django 6.0.2 on 2026-05-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_increase_phone_number_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='button_id',
            field=models.CharField(blank=True, help_text='Button ID for button responses (e.g., mistake_123, cancel_123)', max_length=100),
        ),
    ]
