# Generated by Django 6.0.2 on 2026-05-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_restore_company_closing_fields'),
        ('sales', '0010_sale_total_amount_nullable'),
        ('whatsapp', '0005_alter_whatsappmessage_button_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, help_text='Meta API message ID', max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='whatsappmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('whatsapp_message_id__isnull', False), models.Q(('whatsapp_message_id', ''), _negated=True)), fields=('whatsapp_message_id',), name='unique_whatsapp_message_id_when_set'),
        ),
    ]
