# Generated by Django 6.0.2 on 2026-05-28 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_whatsapp_message_id_nullable_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmParseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(blank=True, max_length=30)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('parse_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_parse_log', to='whatsapp.whatsappmessage')),
            ],
            options={
                'indexes': [models.Index(fields=['intent', '-created_at'], name='whatsapp_ll_intent_74a892_idx')],
            },
        ),
    ]
