# Generated by Django 6.0.1 on 2026-01-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_waitlist_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('ZWG', 'Zimbabwe Gold (ZiG)'), ('ZAR', 'South African Rand (R)'), ('BWP', 'Botswana Pula (P)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)')], default='USD', help_text="Default currency for this company's prices", max_length=3),
        ),
    ]
