# Generated by Django 6.0.1 on 2026-01-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='confirmation_message_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
