# Generated by Django 6.0.1 on 2026-02-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_revert_onboarding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
