# Generated by Django 6.0.1 on 2026-02-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_waitlistentry_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='phone_number',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
