# Generated by Django 6.0.2 on 2026-05-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_drop_orphan_company_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='daily_summary_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
