# Generated by Django 6.0.2 on 2026-05-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_daily_summary_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='daily_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='daily_closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_closing_prompt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_summary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='normal_closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
