# Generated by Django 6.0.2 on 2026-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_restore_company_closing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='first_message_date',
            field=models.DateField(blank=True, help_text='Date of first inbound message — nudge eligibility starts here', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_nudge_date',
            field=models.DateField(blank=True, help_text='Last date a nudge was sent — prevents double-sending', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nudge_stage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Nudge sequence stage — increments after each send'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nudge_opt_out',
            field=models.BooleanField(default=False, help_text="User replied 'stop' — skip nudges for this user"),
        ),
    ]
