# Generated by Django 6.0.2 on 2026-05-29 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_company_first_message_date_company_last_nudge_date_and_more'),
        ('sales', '0010_sale_total_amount_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pending_clarification_sale',
            field=models.OneToOneField(blank=True, help_text='Sale awaiting currency clarification from the owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.sale'),
        ),
    ]
