# Generated by Django 6.0.1 on 2026-01-21 15:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.IntegerField(help_text='Positive for additions, negative for removals')),
                ('reason', models.CharField(choices=[('purchase', 'Purchase/Restock'), ('return', 'Customer Return'), ('damage', 'Damaged/Expired'), ('correction', 'Stock Correction'), ('initial', 'Initial Stock')], default='correction', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to='catalog.product')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
